# Generated by Django 3.1.7 on 2021-03-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compras_id_proveedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='fecha',
            field=models.DateField(default='234', max_length=20),
        ),
    ]
