# Generated by Django 3.1.7 on 2021-03-03 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('compras', '0003_auto_20210301_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='cedula_empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados'),
        ),
    ]
