# Generated by Django 3.1.7 on 2021-03-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_compras_cedula_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='montoTotal',
            new_name='monto_total',
        ),
    ]
