# Generated by Django 3.1.7 on 2021-03-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=40)),
                ('departamento', models.CharField(max_length=40)),
            ],
        ),
    ]
