# Generated by Django 3.1.7 on 2021-03-03 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('cedula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=40)),
                ('fecha_ingre', models.DateTimeField()),
                ('fecha_nacimi', models.DateTimeField()),
                ('rol', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('barrio', models.CharField(max_length=40)),
                ('id_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidad.localidad')),
            ],
        ),
    ]
