# Generated by Django 3.1.7 on 2021-02-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('ruc', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('cedula', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
